TOPIC_LABELS = {
    "State governance, regional policy and public administration": "Valstybės valdymas, regioninė politika ir viešasis administravimas",
    "Environment, forests and climate change": "Aplinka, miškai ir klimato kaita",
    "Energy": "Energetika",
    "Public finance": "Viešieji finansai",
    "Economic competitiveness and state information resources": "Ekonomikos konkurencingumas ir valstybės informaciniai ištekliai",
    "State security and defense": "Valstybės saugumas ir gynyba",
    "Public security": "Viešasis saugumas",
    "Culture": "Kultūra",
    "Social security and employment": "Socialinė apsauga ir užimtumas",
    "Transportation and communications": "Transportas ir ryšiai",
    "Health": "Sveikata",
    "Education, science and sport": "Švietimas, mokslas ir sportas",
    "Justice": "Teisingumas",
    "Foreign policy": "Užsienio politika",
    "Land and food farming, rural development and fisheries": "Žemės ir maisto ūkis, kaimo plėtra ir žuvininkystė",
    "Neatpažinta tema": "Neatpažinta tema",
}
